# Generated by Django 4.1 on 2023-09-01 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_articles_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="site",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="articles",
            name="publish_date",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
