# Generated by Django 4.1 on 2023-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_articles_site_alter_articles_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="like",
            field=models.BooleanField(default=False),
        ),
    ]
