# Generated by Django 3.2.19 on 2023-06-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hobby',
            new_name='hobbies',
        ),
    ]
